1. Using the code from the lesson as a guide and the REST API from https://swapi.dev/ as we did in the lesson, create a dataframe named people that has all of the data for people.
2. Do the same thing, but for planets.
3. Extract the data for starships.
4. Save the data in your files to local csv files so that it will be faster to access in the future.
5. Combine the data from your three separate dataframes into one large dataframe.
6. Acquire the Open Power Systems Data for Germany, which has been rapidly expanding its renewable energy production in recent years. The data set includes country-wide totals of electricity consumption, wind power production, and solar power production for 2006-2017. You can get the data here: https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv
7. Make sure all the work that you have done above is reproducible. That is, you should put the code above into separate functions in the acquire.py file and be able to re-run the functions and get the same data.

In [1]:
import requests
import pandas as pd
import os

import warnings
warnings.filterwarnings('ignore')

In [2]:
url = 'https://swapi.dev/api/people/'
response = requests.get(url)
json = response.json()
json

{'count': 82,
 'next': 'https://swapi.dev/api/people/?page=2',
 'previous': None,
 'results': [{'name': 'Luke Skywalker',
   'height': '172',
   'mass': '77',
   'hair_color': 'blond',
   'skin_color': 'fair',
   'eye_color': 'blue',
   'birth_year': '19BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/6/'],
   'species': [],
   'vehicles': ['https://swapi.dev/api/vehicles/14/',
    'https://swapi.dev/api/vehicles/30/'],
   'starships': ['https://swapi.dev/api/starships/12/',
    'https://swapi.dev/api/starships/22/'],
   'created': '2014-12-09T13:50:51.644000Z',
   'edited': '2014-12-20T21:17:56.891000Z',
   'url': 'https://swapi.dev/api/people/1/'},
  {'name': 'C-3PO',
   'height': '167',
   'mass': '75',
   'hair_color': 'n/a',
   'skin_color': 'gold',
   'eye_color': 'yellow',
   'birth_year': '112BBY',
   'gender': 'n/a',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/4/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'species': ['https://swapi.dev/api/species/2/'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:10:51.357000Z',
   'edited': '2014-12-20T21:17:50.309000Z',
   'url': 'https://swapi.dev/api/people/2/'},
  {'name': 'R2-D2',
   'height': '96',
   'mass': '32',
   'hair_color': 'n/a',
   'skin_color': 'white, blue',
   'eye_color': 'red',
   'birth_year': '33BBY',
   'gender': 'n/a',
   'homeworld': 'https://swapi.dev/api/planets/8/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/4/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'species': ['https://swapi.dev/api/species/2/'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:11:50.376000Z',
   'edited': '2014-12-20T21:17:50.311000Z',
   'url': 'https://swapi.dev/api/people/3/'},
  {'name': 'Darth Vader',
   'height': '202',
   'mass': '136',
   'hair_color': 'none',
   'skin_color': 'white',
   'eye_color': 'yellow',
   'birth_year': '41.9BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/6/'],
   'species': [],
   'vehicles': [],
   'starships': ['https://swapi.dev/api/starships/13/'],
   'created': '2014-12-10T15:18:20.704000Z',
   'edited': '2014-12-20T21:17:50.313000Z',
   'url': 'https://swapi.dev/api/people/4/'},
  {'name': 'Leia Organa',
   'height': '150',
   'mass': '49',
   'hair_color': 'brown',
   'skin_color': 'light',
   'eye_color': 'brown',
   'birth_year': '19BBY',
   'gender': 'female',
   'homeworld': 'https://swapi.dev/api/planets/2/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/6/'],
   'species': [],
   'vehicles': ['https://swapi.dev/api/vehicles/30/'],
   'starships': [],
   'created': '2014-12-10T15:20:09.791000Z',
   'edited': '2014-12-20T21:17:50.315000Z',
   'url': 'https://swapi.dev/api/people/5/'},
  {'name': 'Owen Lars',
   'height': '178',
   'mass': '120',
   'hair_color': 'brown, grey',
   'skin_color': 'light',
   'eye_color': 'blue',
   'birth_year': '52BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'species': [],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:52:14.024000Z',
   'edited': '2014-12-20T21:17:50.317000Z',
   'url': 'https://swapi.dev/api/people/6/'},
  {'name': 'Beru Whitesun lars',
   'height': '165',
   'mass': '75',
   'hair_color': 'brown',
   'skin_color': 'light',
   'eye_color': 'blue',
   'birth_year': '47BBY',
   'gender': 'female',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'species': [],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:53:41.121000Z',
   'edited': '2014-12-20T21:17:50.319000Z',
   'url': 'https://swapi.dev/api/people/7/'},
  {'name': 'R5-D4',
   'height': '97',
   'mass': '32',
   'hair_color': 'n/a',
   'skin_color': 'white, red',
   'eye_color': 'red',
   'birth_year': 'unknown',
   'gender': 'n/a',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/'],
   'species': ['https://swapi.dev/api/species/2/'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:57:50.959000Z',
   'edited': '2014-12-20T21:17:50.321000Z',
   'url': 'https://swapi.dev/api/people/8/'},
  {'name': 'Biggs Darklighter',
   'height': '183',
   'mass': '84',
   'hair_color': 'black',
   'skin_color': 'light',
   'eye_color': 'brown',
   'birth_year': '24BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/'],
   'species': [],
   'vehicles': [],
   'starships': ['https://swapi.dev/api/starships/12/'],
   'created': '2014-12-10T15:59:50.509000Z',
   'edited': '2014-12-20T21:17:50.323000Z',
   'url': 'https://swapi.dev/api/people/9/'},
  {'name': 'Obi-Wan Kenobi',
   'height': '182',
   'mass': '77',
   'hair_color': 'auburn, white',
   'skin_color': 'fair',
   'eye_color': 'blue-gray',
   'birth_year': '57BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.dev/api/planets/20/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/4/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'species': [],
   'vehicles': ['https://swapi.dev/api/vehicles/38/'],
   'starships': ['https://swapi.dev/api/starships/48/',
    'https://swapi.dev/api/starships/59/',
    'https://swapi.dev/api/starships/64/',
    'https://swapi.dev/api/starships/65/',
    'https://swapi.dev/api/starships/74/'],
   'created': '2014-12-10T16:16:29.192000Z',
   'edited': '2014-12-20T21:17:50.325000Z',
   'url': 'https://swapi.dev/api/people/10/'}]}

In [3]:
json.keys()

dict_keys(['count', 'next', 'previous', 'results'])

In [4]:
people = pd.DataFrame(json['results'])
people

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],"[https://swapi.dev/api/vehicles/14/, https://s...","[https://swapi.dev/api/starships/12/, https://...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.dev/api/people/1/
1,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.dev/api/people/2/
2,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,https://swapi.dev/api/planets/8/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.dev/api/people/3/
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[https://swapi.dev/api/starships/13/],2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.dev/api/people/4/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/30/],[],2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.dev/api/people/5/
5,Owen Lars,178,120,"brown, grey",light,blue,52BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-10T15:52:14.024000Z,2014-12-20T21:17:50.317000Z,https://swapi.dev/api/people/6/
6,Beru Whitesun lars,165,75,brown,light,blue,47BBY,female,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-10T15:53:41.121000Z,2014-12-20T21:17:50.319000Z,https://swapi.dev/api/people/7/
7,R5-D4,97,32,n/a,"white, red",red,unknown,n/a,https://swapi.dev/api/planets/1/,[https://swapi.dev/api/films/1/],[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:57:50.959000Z,2014-12-20T21:17:50.321000Z,https://swapi.dev/api/people/8/
8,Biggs Darklighter,183,84,black,light,brown,24BBY,male,https://swapi.dev/api/planets/1/,[https://swapi.dev/api/films/1/],[],[],[https://swapi.dev/api/starships/12/],2014-12-10T15:59:50.509000Z,2014-12-20T21:17:50.323000Z,https://swapi.dev/api/people/9/
9,Obi-Wan Kenobi,182,77,"auburn, white",fair,blue-gray,57BBY,male,https://swapi.dev/api/planets/20/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/38/],"[https://swapi.dev/api/starships/48/, https://...",2014-12-10T16:16:29.192000Z,2014-12-20T21:17:50.325000Z,https://swapi.dev/api/people/10/

In [24]:
while json['next'] != None:
    print(json['next'])
    response = requests.get(json['next'])
    json = response.json()
    people = pd.concat([people, pd.DataFrame(json['results'])], ignore_index = True)

https://swapi.dev/api/starships/?page=2
https://swapi.dev/api/starships/?page=3
https://swapi.dev/api/starships/?page=4

In [8]:
url = 'https://swapi.dev/api/planets/'
response = requests.get(url)
json = response.json()
json.keys()

dict_keys(['count', 'next', 'previous', 'results'])

In [9]:
planets = pd.DataFrame(json['results'])
planets

,name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents,films,created,edited,url
0,Tatooine,23,304,10465,arid,1 standard,desert,1,200000,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-09T13:50:49.641000Z,2014-12-20T20:58:18.411000Z,https://swapi.dev/api/planets/1/
1,Alderaan,24,364,12500,temperate,1 standard,"grasslands, mountains",40,2000000000,"[https://swapi.dev/api/people/5/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T11:35:48.479000Z,2014-12-20T20:58:18.420000Z,https://swapi.dev/api/planets/2/
2,Yavin IV,24,4818,10200,"temperate, tropical",1 standard,"jungle, rainforests",8,1000,[],[https://swapi.dev/api/films/1/],2014-12-10T11:37:19.144000Z,2014-12-20T20:58:18.421000Z,https://swapi.dev/api/planets/3/
3,Hoth,23,549,7200,frozen,1.1 standard,"tundra, ice caves, mountain ranges",100,unknown,[],[https://swapi.dev/api/films/2/],2014-12-10T11:39:13.934000Z,2014-12-20T20:58:18.423000Z,https://swapi.dev/api/planets/4/
4,Dagobah,23,341,8900,murky,N/A,"swamp, jungles",8,unknown,[],"[https://swapi.dev/api/films/2/, https://swapi...",2014-12-10T11:42:22.590000Z,2014-12-20T20:58:18.425000Z,https://swapi.dev/api/planets/5/
5,Bespin,12,5110,118000,temperate,"1.5 (surface), 1 standard (Cloud City)",gas giant,0,6000000,[https://swapi.dev/api/people/26/],[https://swapi.dev/api/films/2/],2014-12-10T11:43:55.240000Z,2014-12-20T20:58:18.427000Z,https://swapi.dev/api/planets/6/
6,Endor,18,402,4900,temperate,0.85 standard,"forests, mountains, lakes",8,30000000,[https://swapi.dev/api/people/30/],[https://swapi.dev/api/films/3/],2014-12-10T11:50:29.349000Z,2014-12-20T20:58:18.429000Z,https://swapi.dev/api/planets/7/
7,Naboo,26,312,12120,temperate,1 standard,"grassy hills, swamps, forests, mountains",12,4500000000,"[https://swapi.dev/api/people/3/, https://swap...","[https://swapi.dev/api/films/3/, https://swapi...",2014-12-10T11:52:31.066000Z,2014-12-20T20:58:18.430000Z,https://swapi.dev/api/planets/8/
8,Coruscant,24,368,12240,temperate,1 standard,"cityscape, mountains",unknown,1000000000000,"[https://swapi.dev/api/people/34/, https://swa...","[https://swapi.dev/api/films/3/, https://swapi...",2014-12-10T11:54:13.921000Z,2014-12-20T20:58:18.432000Z,https://swapi.dev/api/planets/9/
9,Kamino,27,463,19720,temperate,1 standard,ocean,100,1000000000,"[https://swapi.dev/api/people/22/, https://swa...",[https://swapi.dev/api/films/5/],2014-12-10T12:45:06.577000Z,2014-12-20T20:58:18.434000Z,https://swapi.dev/api/planets/10/

In [10]:
url = 'https://swapi.dev/api/starships/'
response = requests.get(url)
json = response.json()
json.keys()

dict_keys(['count', 'next', 'previous', 'results'])

In [11]:
starships = pd.DataFrame(json['results'])
starships

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films,created,edited,url
0,CR90 corvette,CR90 corvette,Corellian Engineering Corporation,3500000,150,950,30-165,600,3000000,1 year,2.0,60,corvette,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T14:20:33.369000Z,2014-12-20T21:23:49.867000Z,https://swapi.dev/api/starships/2/
1,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,150000000,"1,600",975,"47,060",n/a,36000000,2 years,2.0,60,Star Destroyer,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T15:08:19.848000Z,2014-12-20T21:23:49.870000Z,https://swapi.dev/api/starships/3/
2,Sentinel-class landing craft,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",240000,38,1000,5,75,180000,1 month,1.0,70,landing craft,[],[https://swapi.dev/api/films/1/],2014-12-10T15:48:00.586000Z,2014-12-20T21:23:49.873000Z,https://swapi.dev/api/starships/5/
3,Death Star,DS-1 Orbital Battle Station,"Imperial Department of Military Research, Sien...",1000000000000,120000,n/a,"342,953","843,342",1000000000000,3 years,4.0,10,Deep Space Mobile Battlestation,[],[https://swapi.dev/api/films/1/],2014-12-10T16:36:50.509000Z,2014-12-20T21:26:24.783000Z,https://swapi.dev/api/starships/9/
4,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,100000,34.37,1050,4,6,100000,2 months,0.5,75,Light freighter,"[https://swapi.dev/api/people/13/, https://swa...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,https://swapi.dev/api/starships/10/
5,Y-wing,BTL Y-wing,Koensayr Manufacturing,134999,14,1000km,2,0,110,1 week,1.0,80,assault starfighter,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-12T11:00:39.817000Z,2014-12-20T21:23:49.883000Z,https://swapi.dev/api/starships/11/
6,X-wing,T-65 X-wing,Incom Corporation,149999,12.5,1050,1,0,110,1 week,1.0,100,Starfighter,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-12T11:19:05.340000Z,2014-12-20T21:23:49.886000Z,https://swapi.dev/api/starships/12/
7,TIE Advanced x1,Twin Ion Engine Advanced x1,Sienar Fleet Systems,unknown,9.2,1200,1,0,150,5 days,1.0,105,Starfighter,[https://swapi.dev/api/people/4/],[https://swapi.dev/api/films/1/],2014-12-12T11:21:32.991000Z,2014-12-20T21:23:49.889000Z,https://swapi.dev/api/starships/13/
8,Executor,Executor-class star dreadnought,"Kuat Drive Yards, Fondor Shipyards",1143350000,19000,n/a,"279,144",38000,250000000,6 years,2.0,40,Star dreadnought,[],"[https://swapi.dev/api/films/2/, https://swapi...",2014-12-15T12:31:42.547000Z,2014-12-20T21:23:49.893000Z,https://swapi.dev/api/starships/15/
9,Rebel transport,GR-75 medium transport,"Gallofree Yards, Inc.",unknown,90,650,6,90,19000000,6 months,4.0,20,Medium transport,[],"[https://swapi.dev/api/films/2/, https://swapi...",2014-12-15T12:34:52.264000Z,2014-12-20T21:23:49.895000Z,https://swapi.dev/api/starships/17/

In [12]:
people.to_csv('people.csv', index = False)
planets.to_csv('planets.csv', index = False)
starships.to_csv('starships.csv', index = False)

In [13]:
pd.options.display.max_columns = None
starwars_df = pd.concat([people, planets, starships], axis = 1)
starwars_df

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url,name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents,films,created,edited,url,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films,created,edited,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],"[https://swapi.dev/api/vehicles/14/, https://s...","[https://swapi.dev/api/starships/12/, https://...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.dev/api/people/1/,Tatooine,23,304,10465,arid,1 standard,desert,1,200000,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-09T13:50:49.641000Z,2014-12-20T20:58:18.411000Z,https://swapi.dev/api/planets/1/,CR90 corvette,CR90 corvette,Corellian Engineering Corporation,3500000,150,950,30-165,600,3000000,1 year,2.0,60,corvette,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T14:20:33.369000Z,2014-12-20T21:23:49.867000Z,https://swapi.dev/api/starships/2/
1,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.dev/api/people/2/,Alderaan,24,364,12500,temperate,1 standard,"grasslands, mountains",40,2000000000,"[https://swapi.dev/api/people/5/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T11:35:48.479000Z,2014-12-20T20:58:18.420000Z,https://swapi.dev/api/planets/2/,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,150000000,"1,600",975,"47,060",n/a,36000000,2 years,2.0,60,Star Destroyer,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T15:08:19.848000Z,2014-12-20T21:23:49.870000Z,https://swapi.dev/api/starships/3/
2,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,https://swapi.dev/api/planets/8/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.dev/api/people/3/,Yavin IV,24,4818,10200,"temperate, tropical",1 standard,"jungle, rainforests",8,1000,[],[https://swapi.dev/api/films/1/],2014-12-10T11:37:19.144000Z,2014-12-20T20:58:18.421000Z,https://swapi.dev/api/planets/3/,Sentinel-class landing craft,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",240000,38,1000,5,75,180000,1 month,1.0,70,landing craft,[],[https://swapi.dev/api/films/1/],2014-12-10T15:48:00.586000Z,2014-12-20T21:23:49.873000Z,https://swapi.dev/api/starships/5/
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[https://swapi.dev/api/starships/13/],2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.dev/api/people/4/,Hoth,23,549,7200,frozen,1.1 standard,"tundra, ice caves, mountain ranges",100,unknown,[],[https://swapi.dev/api/films/2/],2014-12-10T11:39:13.934000Z,2014-12-20T20:58:18.423000Z,https://swapi.dev/api/planets/4/,Death Star,DS-1 Orbital Battle Station,"Imperial Department of Military Research, Sien...",1000000000000,120000,n/a,"342,953","843,342",1000000000000,3 years,4.0,10,Deep Space Mobile Battlestation,[],[https://swapi.dev/api/films/1/],2014-12-10T16:36:50.509000Z,2014-12-20T21:26:24.783000Z,https://swapi.dev/api/starships/9/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/30/],[],2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.dev/api/people/5/,Dagobah,23,341,8900,murky,N/A,"swamp, jungles",8,unknown,[],"[https://swapi.dev/api/films/2/, https://swapi...",2014-12-10T11:42:22.590000Z,2014-12-20T20:58:18.425000Z,https://swapi.dev/api/planets/5/,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,100000,34.37,1050,4,6,100000,2 months,0.5,75,Light freighter,"[https://swapi.dev/api/people/13/, https://swa...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,https://swapi.dev/api/starships/10/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Grievous,216,159,none,"brown, white","green, yellow",unknown,male,https://swapi.dev/api/planets/59/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/36/],[https://swapi.dev/api/vehicles/60/],[https://swapi.dev/api/starships/74/],2014-12-20T19:43:53.348000Z,2014-12-20T21:17:50.488000Z,https://swapi.dev/api/people/79/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Tarfful,234,136,brown,brown,blue,unknown,male,https://swapi.dev/api/planets/14/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/3/],[],[],2014-12-20T19:46:34.209000Z,2014-12-20T21:17:50.491000Z,https://swapi.dev/api/people/80/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Raymus Antilles,188,79,brown,light,brown,unknown,male,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-20T19:49:35.583000Z,2014-12-20T21:17:50.493000Z,https://swapi.dev/api/people/81/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Sly Moore,178,48,none,pale,white,unknown,female,https://swapi.dev/api/planets/60/,"[https://swapi.dev/api/films/5/, https://swapi...",[],[],[],2014-12-20T20:18:37.619000Z,2014-12-20T21:17:50.496000Z,https://swapi.dev/api/people/82/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Tion Medon,206,80,none,grey,black,unknown,male,https://swapi.dev/api/planets/12/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/37/],[],[],2014-12-20T20:35:04.260000Z,2014-12-20T21:17:50.498000Z,https://swapi.dev/api/people/83/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
def get_people_data():
    
    if os.path.isfile('people.csv'):
        
        return pd.read_csv('people.csv')
    
    else:
       
        url = 'https://swapi.dev/api/people/'
        response = requests.get(url)
        json = response.json()

        people = pd.DataFrame(json['results'])
        
        people.to_csv('people.csv', index = False)
   
    return people

In [15]:
get_people_data()

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"['https://swapi.dev/api/films/1/', 'https://sw...",[],"['https://swapi.dev/api/vehicles/14/', 'https:...","['https://swapi.dev/api/starships/12/', 'https...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.dev/api/people/1/
1,C-3PO,167,75,NaN,gold,yellow,112BBY,NaN,https://swapi.dev/api/planets/1/,"['https://swapi.dev/api/films/1/', 'https://sw...",['https://swapi.dev/api/species/2/'],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.dev/api/people/2/
2,R2-D2,96,32,NaN,"white, blue",red,33BBY,NaN,https://swapi.dev/api/planets/8/,"['https://swapi.dev/api/films/1/', 'https://sw...",['https://swapi.dev/api/species/2/'],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.dev/api/people/3/
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.dev/api/planets/1/,"['https://swapi.dev/api/films/1/', 'https://sw...",[],[],['https://swapi.dev/api/starships/13/'],2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.dev/api/people/4/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,"['https://swapi.dev/api/films/1/', 'https://sw...",[],['https://swapi.dev/api/vehicles/30/'],[],2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.dev/api/people/5/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Grievous,216,159,none,"brown, white","green, yellow",unknown,male,https://swapi.dev/api/planets/59/,['https://swapi.dev/api/films/6/'],['https://swapi.dev/api/species/36/'],['https://swapi.dev/api/vehicles/60/'],['https://swapi.dev/api/starships/74/'],2014-12-20T19:43:53.348000Z,2014-12-20T21:17:50.488000Z,https://swapi.dev/api/people/79/
68,Tarfful,234,136,brown,brown,blue,unknown,male,https://swapi.dev/api/planets/14/,['https://swapi.dev/api/films/6/'],['https://swapi.dev/api/species/3/'],[],[],2014-12-20T19:46:34.209000Z,2014-12-20T21:17:50.491000Z,https://swapi.dev/api/people/80/
69,Raymus Antilles,188,79,brown,light,brown,unknown,male,https://swapi.dev/api/planets/2/,"['https://swapi.dev/api/films/1/', 'https://sw...",[],[],[],2014-12-20T19:49:35.583000Z,2014-12-20T21:17:50.493000Z,https://swapi.dev/api/people/81/
70,Sly Moore,178,48,none,pale,white,unknown,female,https://swapi.dev/api/planets/60/,"['https://swapi.dev/api/films/5/', 'https://sw...",[],[],[],2014-12-20T20:18:37.619000Z,2014-12-20T21:17:50.496000Z,https://swapi.dev/api/people/82/
71,Tion Medon,206,80,none,grey,black,unknown,male,https://swapi.dev/api/planets/12/,['https://swapi.dev/api/films/6/'],['https://swapi.dev/api/species/37/'],[],[],2014-12-20T20:35:04.260000Z,2014-12-20T21:17:50.498000Z,https://swapi.dev/api/people/83/

In [16]:
def get_planets_data():
    
    if os.path.isfile('planets.csv'):
        
        return pd.read_csv('planets.csv')
    
    else:
       
        url = 'https://swapi.dev/api/planets/'
        response = requests.get(url)
        json = response.json()

        planets = pd.DataFrame(json['results'])
        
        planets.to_csv('planets.csv', index = False)
   
    return planets

In [17]:
get_planets_data()

,name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents,films,created,edited,url
0,Tatooine,23,304,10465,arid,1 standard,desert,1,200000,"['https://swapi.dev/api/people/1/', 'https://s...","['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-09T13:50:49.641000Z,2014-12-20T20:58:18.411000Z,https://swapi.dev/api/planets/1/
1,Alderaan,24,364,12500,temperate,1 standard,"grasslands, mountains",40,2000000000,"['https://swapi.dev/api/people/5/', 'https://s...","['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-10T11:35:48.479000Z,2014-12-20T20:58:18.420000Z,https://swapi.dev/api/planets/2/
2,Yavin IV,24,4818,10200,"temperate, tropical",1 standard,"jungle, rainforests",8,1000,[],['https://swapi.dev/api/films/1/'],2014-12-10T11:37:19.144000Z,2014-12-20T20:58:18.421000Z,https://swapi.dev/api/planets/3/
3,Hoth,23,549,7200,frozen,1.1 standard,"tundra, ice caves, mountain ranges",100,unknown,[],['https://swapi.dev/api/films/2/'],2014-12-10T11:39:13.934000Z,2014-12-20T20:58:18.423000Z,https://swapi.dev/api/planets/4/
4,Dagobah,23,341,8900,murky,NaN,"swamp, jungles",8,unknown,[],"['https://swapi.dev/api/films/2/', 'https://sw...",2014-12-10T11:42:22.590000Z,2014-12-20T20:58:18.425000Z,https://swapi.dev/api/planets/5/
5,Bespin,12,5110,118000,temperate,"1.5 (surface), 1 standard (Cloud City)",gas giant,0,6000000,['https://swapi.dev/api/people/26/'],['https://swapi.dev/api/films/2/'],2014-12-10T11:43:55.240000Z,2014-12-20T20:58:18.427000Z,https://swapi.dev/api/planets/6/
6,Endor,18,402,4900,temperate,0.85 standard,"forests, mountains, lakes",8,30000000,['https://swapi.dev/api/people/30/'],['https://swapi.dev/api/films/3/'],2014-12-10T11:50:29.349000Z,2014-12-20T20:58:18.429000Z,https://swapi.dev/api/planets/7/
7,Naboo,26,312,12120,temperate,1 standard,"grassy hills, swamps, forests, mountains",12,4500000000,"['https://swapi.dev/api/people/3/', 'https://s...","['https://swapi.dev/api/films/3/', 'https://sw...",2014-12-10T11:52:31.066000Z,2014-12-20T20:58:18.430000Z,https://swapi.dev/api/planets/8/
8,Coruscant,24,368,12240,temperate,1 standard,"cityscape, mountains",unknown,1000000000000,"['https://swapi.dev/api/people/34/', 'https://...","['https://swapi.dev/api/films/3/', 'https://sw...",2014-12-10T11:54:13.921000Z,2014-12-20T20:58:18.432000Z,https://swapi.dev/api/planets/9/
9,Kamino,27,463,19720,temperate,1 standard,ocean,100,1000000000,"['https://swapi.dev/api/people/22/', 'https://...",['https://swapi.dev/api/films/5/'],2014-12-10T12:45:06.577000Z,2014-12-20T20:58:18.434000Z,https://swapi.dev/api/planets/10/

In [18]:
def get_starships_data():
    
    if os.path.isfile('starships.csv'):
        
        return pd.read_csv('starships.csv')
    
    else:
       
        url = 'https://swapi.dev/api/starships/'
        response = requests.get(url)
        json = response.json()

        starships = pd.DataFrame(json['results'])
        
        starships.to_csv('people.csv', index = False)
   
    return starships

In [19]:
get_starships_data()

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films,created,edited,url
0,CR90 corvette,CR90 corvette,Corellian Engineering Corporation,3500000,150,950,30-165,600,3000000,1 year,2.0,60,corvette,[],"['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-10T14:20:33.369000Z,2014-12-20T21:23:49.867000Z,https://swapi.dev/api/starships/2/
1,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,150000000,"1,600",975,"47,060",NaN,36000000,2 years,2.0,60,Star Destroyer,[],"['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-10T15:08:19.848000Z,2014-12-20T21:23:49.870000Z,https://swapi.dev/api/starships/3/
2,Sentinel-class landing craft,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",240000,38,1000,5,75,180000,1 month,1.0,70,landing craft,[],['https://swapi.dev/api/films/1/'],2014-12-10T15:48:00.586000Z,2014-12-20T21:23:49.873000Z,https://swapi.dev/api/starships/5/
3,Death Star,DS-1 Orbital Battle Station,"Imperial Department of Military Research, Sien...",1000000000000,120000,NaN,"342,953","843,342",1000000000000,3 years,4.0,10,Deep Space Mobile Battlestation,[],['https://swapi.dev/api/films/1/'],2014-12-10T16:36:50.509000Z,2014-12-20T21:26:24.783000Z,https://swapi.dev/api/starships/9/
4,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,100000,34.37,1050,4,6,100000,2 months,0.5,75,Light freighter,"['https://swapi.dev/api/people/13/', 'https://...","['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,https://swapi.dev/api/starships/10/
5,Y-wing,BTL Y-wing,Koensayr Manufacturing,134999,14,1000km,2,0,110,1 week,1.0,80,assault starfighter,[],"['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-12T11:00:39.817000Z,2014-12-20T21:23:49.883000Z,https://swapi.dev/api/starships/11/
6,X-wing,T-65 X-wing,Incom Corporation,149999,12.5,1050,1,0,110,1 week,1.0,100,Starfighter,"['https://swapi.dev/api/people/1/', 'https://s...","['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-12T11:19:05.340000Z,2014-12-20T21:23:49.886000Z,https://swapi.dev/api/starships/12/
7,TIE Advanced x1,Twin Ion Engine Advanced x1,Sienar Fleet Systems,unknown,9.2,1200,1,0,150,5 days,1.0,105,Starfighter,['https://swapi.dev/api/people/4/'],['https://swapi.dev/api/films/1/'],2014-12-12T11:21:32.991000Z,2014-12-20T21:23:49.889000Z,https://swapi.dev/api/starships/13/
8,Executor,Executor-class star dreadnought,"Kuat Drive Yards, Fondor Shipyards",1143350000,19000,NaN,"279,144",38000,250000000,6 years,2.0,40,Star dreadnought,[],"['https://swapi.dev/api/films/2/', 'https://sw...",2014-12-15T12:31:42.547000Z,2014-12-20T21:23:49.893000Z,https://swapi.dev/api/starships/15/
9,Rebel transport,GR-75 medium transport,"Gallofree Yards, Inc.",unknown,90,650,6,90,19000000,6 months,4.0,20,Medium transport,[],"['https://swapi.dev/api/films/2/', 'https://sw...",2014-12-15T12:34:52.264000Z,2014-12-20T21:23:49.895000Z,https://swapi.dev/api/starships/17/

In [20]:
def combine_df(df_x, df_y, df_z):
    
    pd.options.display.max_columns = None
    
    starwars_df = pd.concat([df_x, df_y, df_z], axis = 1)
    
    return starwars_df

In [21]:
combine_df(people, starships, planets)

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films,created,edited,url,name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents,films,created,edited,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],"[https://swapi.dev/api/vehicles/14/, https://s...","[https://swapi.dev/api/starships/12/, https://...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.dev/api/people/1/,CR90 corvette,CR90 corvette,Corellian Engineering Corporation,3500000,150,950,30-165,600,3000000,1 year,2.0,60,corvette,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T14:20:33.369000Z,2014-12-20T21:23:49.867000Z,https://swapi.dev/api/starships/2/,Tatooine,23,304,10465,arid,1 standard,desert,1,200000,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-09T13:50:49.641000Z,2014-12-20T20:58:18.411000Z,https://swapi.dev/api/planets/1/
1,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.dev/api/people/2/,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,150000000,"1,600",975,"47,060",n/a,36000000,2 years,2.0,60,Star Destroyer,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T15:08:19.848000Z,2014-12-20T21:23:49.870000Z,https://swapi.dev/api/starships/3/,Alderaan,24,364,12500,temperate,1 standard,"grasslands, mountains",40,2000000000,"[https://swapi.dev/api/people/5/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T11:35:48.479000Z,2014-12-20T20:58:18.420000Z,https://swapi.dev/api/planets/2/
2,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,https://swapi.dev/api/planets/8/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.dev/api/people/3/,Sentinel-class landing craft,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",240000,38,1000,5,75,180000,1 month,1.0,70,landing craft,[],[https://swapi.dev/api/films/1/],2014-12-10T15:48:00.586000Z,2014-12-20T21:23:49.873000Z,https://swapi.dev/api/starships/5/,Yavin IV,24,4818,10200,"temperate, tropical",1 standard,"jungle, rainforests",8,1000,[],[https://swapi.dev/api/films/1/],2014-12-10T11:37:19.144000Z,2014-12-20T20:58:18.421000Z,https://swapi.dev/api/planets/3/
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[https://swapi.dev/api/starships/13/],2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.dev/api/people/4/,Death Star,DS-1 Orbital Battle Station,"Imperial Department of Military Research, Sien...",1000000000000,120000,n/a,"342,953","843,342",1000000000000,3 years,4.0,10,Deep Space Mobile Battlestation,[],[https://swapi.dev/api/films/1/],2014-12-10T16:36:50.509000Z,2014-12-20T21:26:24.783000Z,https://swapi.dev/api/starships/9/,Hoth,23,549,7200,frozen,1.1 standard,"tundra, ice caves, mountain ranges",100,unknown,[],[https://swapi.dev/api/films/2/],2014-12-10T11:39:13.934000Z,2014-12-20T20:58:18.423000Z,https://swapi.dev/api/planets/4/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/30/],[],2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.dev/api/people/5/,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,100000,34.37,1050,4,6,100000,2 months,0.5,75,Light freighter,"[https://swapi.dev/api/people/13/, https://swa...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,https://swapi.dev/api/starships/10/,Dagobah,23,341,8900,murky,N/A,"swamp, jungles",8,unknown,[],"[https://swapi.dev/api/films/2/, https://swapi...",2014-12-10T11:42:22.590000Z,2014-12-20T20:58:18.425000Z,https://swapi.dev/api/planets/5/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Grievous,216,159,none,"brown, white","green, yellow",unknown,male,https://swapi.dev/api/planets/59/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/36/],[https://swapi.dev/api/vehicles/60/],[https://swapi.dev/api/starships/74/],2014-12-20T19:43:53.348000Z,2014-12-20T21:17:50.488000Z,https://swapi.dev/api/people/79/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Tarfful,234,136,brown,brown,blue,unknown,male,https://swapi.dev/api/planets/14/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/3/],[],[],2014-12-20T19:46:34.209000Z,2014-12-20T21:17:50.491000Z,https://swapi.dev/api/people/80/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Raymus Antilles,188,79,brown,light,brown,unknown,male,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-20T19:49:35.583000Z,2014-12-20T21:17:50.493000Z,https://swapi.dev/api/people/81/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Sly Moore,178,48,none,pale,white,unknown,female,https://swapi.dev/api/planets/60/,"[https://swapi.dev/api/films/5/, https://swapi...",[],[],[],2014-12-20T20:18:37.619000Z,2014-12-20T21:17:50.496000Z,https://swapi.dev/api/people/82/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Tion Medon,206,80,none,grey,black,unknown,male,https://swapi.dev/api/planets/12/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/37/],[],[],2014-12-20T20:35:04.260000Z,2014-12-20T21:17:50.498000Z,https://swapi.dev/api/people/83/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
def get_renewable_energy_data():
    
    if os.path.isfile('renewable_energy_production.csv'):
        
        return pd.read_csv('renewable_energy_production.csv')
    
    else:
       
        url = 'https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv'

        df = pd.DataFrame(pd.read_csv(url))
        
        df.to_csv('renewable_energy_production.csv', index = False)
   
    return df

In [23]:
pd.options.display.max_rows = None
get_renewable_energy_data()

            Date  Consumption     Wind    Solar  Wind+Solar
0     2006-01-01   1069.18400      NaN      NaN         NaN
1     2006-01-02   1380.52100      NaN      NaN         NaN
2     2006-01-03   1442.53300      NaN      NaN         NaN
3     2006-01-04   1457.21700      NaN      NaN         NaN
4     2006-01-05   1477.13100      NaN      NaN         NaN
5     2006-01-06   1403.42700      NaN      NaN         NaN
6     2006-01-07   1300.28700      NaN      NaN         NaN
7     2006-01-08   1207.98500      NaN      NaN         NaN
8     2006-01-09   1529.32300      NaN      NaN         NaN
9     2006-01-10   1576.91100      NaN      NaN         NaN
10    2006-01-11   1577.17600      NaN      NaN         NaN
11    2006-01-12   1553.28000      NaN      NaN         NaN
12    2006-01-13   1545.00200      NaN      NaN         NaN
13    2006-01-14   1359.94500      NaN      NaN         NaN
14    2006-01-15   1265.47500      NaN      NaN         NaN
15    2006-01-16   1563.73800      NaN      NaN         NaN
16    2006-01-17   1598.30300      NaN      NaN         NaN
17    2006-01-18   1572.98400      NaN      NaN         NaN
18    2006-01-19   1558.29000      NaN      NaN         NaN
19    2006-01-20   1540.60400      NaN      NaN         NaN
20    2006-01-21   1348.18800      NaN      NaN         NaN
21    2006-01-22   1248.11100      NaN      NaN         NaN
22    2006-01-23   1569.69100      NaN      NaN         NaN
23    2006-01-24   1603.25200      NaN      NaN         NaN
24    2006-01-25   1613.31200      NaN      NaN         NaN
25    2006-01-26   1601.67300      NaN      NaN         NaN
26    2006-01-27   1586.06500      NaN      NaN         NaN
27    2006-01-28   1373.03000      NaN      NaN         NaN
28    2006-01-29   1252.21500      NaN      NaN         NaN
29    2006-01-30   1554.72200      NaN      NaN         NaN
30    2006-01-31   1575.12900      NaN      NaN         NaN
31    2006-02-01   1582.13400      NaN      NaN         NaN
32    2006-02-02   1595.71700      NaN      NaN         NaN
33    2006-02-03   1577.78600      NaN      NaN         NaN
34    2006-02-04   1366.32200      NaN      NaN         NaN
35    2006-02-05   1258.01300      NaN      NaN         NaN
36    2006-02-06   1557.52500      NaN      NaN         NaN
37    2006-02-07   1606.66700      NaN      NaN         NaN
38    2006-02-08   1590.89600      NaN      NaN         NaN
39    2006-02-09   1599.12900      NaN      NaN         NaN
40    2006-02-10   1554.63100      NaN      NaN         NaN
41    2006-02-11   1346.10400      NaN      NaN         NaN
42    2006-02-12   1232.56800      NaN      NaN         NaN
43    2006-02-13   1521.45600      NaN      NaN         NaN
44    2006-02-14   1551.37300      NaN      NaN         NaN
45    2006-02-15   1562.65600      NaN      NaN         NaN
46    2006-02-16   1523.71900      NaN      NaN         NaN
47    2006-02-17   1495.91300      NaN      NaN         NaN
48    2006-02-18   1297.38500      NaN      NaN         NaN
49    2006-02-19   1173.05000      NaN      NaN         NaN
50    2006-02-20   1501.24600      NaN      NaN         NaN
51    2006-02-21   1544.11200      NaN      NaN         NaN
52    2006-02-22   1543.10700      NaN      NaN         NaN
53    2006-02-23   1523.49100      NaN      NaN         NaN
54    2006-02-24   1507.23500      NaN      NaN         NaN
55    2006-02-25   1309.60300      NaN      NaN         NaN
56    2006-02-26   1204.76600      NaN      NaN         NaN
57    2006-02-27   1444.89900      NaN      NaN         NaN
58    2006-02-28   1507.49000      NaN      NaN         NaN
59    2006-03-01   1531.17300      NaN      NaN         NaN
60    2006-03-02   1539.95100      NaN      NaN         NaN
61    2006-03-03   1510.88400      NaN      NaN         NaN
62    2006-03-04   1323.30300      NaN      NaN         NaN
63    2006-03-05   1220.39500      NaN      NaN         NaN
64    2006-03-06   1502.19100      NaN      NaN         NaN
65    2006-03-07   1514.01200      NaN      NaN         NaN
66    2006-03-08   1545.83400      NaN      NaN         NaN
67    2006-03-09   1498.44400      NaN      NaN         NaN
68    2006-03-10   1475.32700      NaN      NaN         NaN
69    2006-03-11   1320.36800      NaN      NaN         NaN
70    2006-03-12   1218.40700      NaN      NaN         NaN
71    2006-03-13   1494.83200      NaN      NaN         NaN
72    2006-03-14   1514.06600      NaN      NaN         NaN
73    2006-03-15   1518.04000      NaN      NaN         NaN
74    2006-03-16   1516.89800      NaN      NaN         NaN
75    2006-03-17   1495.32400      NaN      NaN         NaN
76    2006-03-18   1280.71700      NaN      NaN         NaN
77    2006-03-19   1160.07800      NaN      NaN         NaN
78    2006-03-20   1446.23800      NaN      NaN         NaN
79    2006-03-21   1470.34000      NaN      NaN         NaN
80    2006-03-22   1471.66700      NaN      NaN         NaN
81    2006-03-23   1456.01600      NaN      NaN         NaN
82    2006-03-24   1444.75000      NaN      NaN         NaN
83    2006-03-25   1231.06700      NaN      NaN         NaN
84    2006-03-26   1116.74300      NaN      NaN         NaN
85    2006-03-27   1400.98200      NaN      NaN         NaN
86    2006-03-28   1435.15200      NaN      NaN         NaN
87    2006-03-29   1438.40500      NaN      NaN         NaN
88    2006-03-30   1457.45400      NaN      NaN         NaN
89    2006-03-31   1429.06600      NaN      NaN         NaN
90    2006-04-01   1207.76900      NaN      NaN         NaN
91    2006-04-02   1110.02600      NaN      NaN         NaN
92    2006-04-03   1422.78900      NaN      NaN         NaN
93    2006-04-04   1436.69900      NaN      NaN         NaN
94    2006-04-05   1447.79800      NaN      NaN         NaN
95    2006-04-06   1432.85300      NaN      NaN         NaN
96    2006-04-07   1394.98000      NaN      NaN         NaN
97    2006-04-08   1195.95900      NaN      NaN         NaN
98    2006-04-09   1104.10600      NaN      NaN         NaN
99    2006-04-10   1408.16900      NaN      NaN         NaN
100   2006-04-11   1419.30100      NaN      NaN         NaN
101   2006-04-12   1425.71200      NaN      NaN         NaN
102   2006-04-13   1415.54200      NaN      NaN         NaN
103   2006-04-14   1118.39600      NaN      NaN         NaN
104   2006-04-15   1086.01800      NaN      NaN         NaN
105   2006-04-16    986.87500      NaN      NaN         NaN
106   2006-04-17   1009.09400      NaN      NaN         NaN
107   2006-04-18   1349.56300      NaN      NaN         NaN
108   2006-04-19   1368.45600      NaN      NaN         NaN
109   2006-04-20   1362.21700      NaN      NaN         NaN
110   2006-04-21   1333.26600      NaN      NaN         NaN
111   2006-04-22   1152.94300      NaN      NaN         NaN
112   2006-04-23   1042.41400      NaN      NaN         NaN
113   2006-04-24   1345.85100      NaN      NaN         NaN
114   2006-04-25   1359.80600      NaN      NaN         NaN
115   2006-04-26   1374.32200      NaN      NaN         NaN
116   2006-04-27   1384.68100      NaN      NaN         NaN
117   2006-04-28   1362.57000      NaN      NaN         NaN
118   2006-04-29   1167.24000      NaN      NaN         NaN
119   2006-04-30   1026.35200      NaN      NaN         NaN
120   2006-05-01    986.69800      NaN      NaN         NaN
121   2006-05-02   1329.82100      NaN      NaN         NaN
122   2006-05-03   1348.18800      NaN      NaN         NaN
123   2006-05-04   1348.34300      NaN      NaN         NaN
124   2006-05-05   1330.52000      NaN      NaN         NaN
125   2006-05-06   1115.44200      NaN      NaN         NaN
126   2006-05-07    998.30800      NaN      NaN         NaN
127   2006-05-08   1321.78200      NaN      NaN         NaN
128   2006-05-09   1353.22900      NaN      NaN         NaN
129   2006-05-10   1351.40000      NaN      NaN         NaN
130   2006-05-11   1337.50200      NaN      NaN         NaN
131   2006-05-12   1320.00600      NaN      NaN         NaN
132   2006-05-13   1123.92600      NaN      NaN         NaN
133   2006-05-14   1010.28400      NaN      NaN         NaN
134   2006-05-15   1317.84900      NaN      NaN         NaN
135   2006-05-16   1360.65000      NaN      NaN         NaN
136   2006-05-17   1346.09800      NaN      NaN         NaN
137   2006-05-18   1365.40600      NaN      NaN         NaN
138   2006-05-19   1348.46500      NaN      NaN         NaN
139   2006-05-20   1175.27300      NaN      NaN         NaN
140   2006-05-21   1050.17000      NaN      NaN         NaN
141   2006-05-22   1358.08200      NaN      NaN         NaN
142   2006-05-23   1374.49500      NaN      NaN         NaN
143   2006-05-24   1339.56500      NaN      NaN         NaN
144   2006-05-25   1053.35100      NaN      NaN         NaN
145   2006-05-26   1213.46500      NaN      NaN         NaN
146   2006-05-27   1108.26600      NaN      NaN         NaN
147   2006-05-28   1065.34300      NaN      NaN         NaN
148   2006-05-29   1349.24700      NaN      NaN         NaN
149   2006-05-30   1376.79400      NaN      NaN         NaN
150   2006-05-31   1380.17500      NaN      NaN         NaN
151   2006-06-01   1367.75100      NaN      NaN         NaN
152   2006-06-02   1323.23100      NaN      NaN         NaN
153   2006-06-03   1100.88900      NaN      NaN         NaN
154   2006-06-04    955.37300      NaN      NaN         NaN
155   2006-06-05    975.63200      NaN      NaN         NaN
156   2006-06-06   1306.36200      NaN      NaN         NaN
157   2006-06-07   1325.81800      NaN      NaN         NaN
158   2006-06-08   1328.54600      NaN      NaN         NaN
159   2006-06-09   1311.78400      NaN      NaN         NaN
160   2006-06-10   1114.52700      NaN      NaN         NaN
161   2006-06-11   1004.85300      NaN      NaN         NaN
162   2006-06-12   1329.59100      NaN      NaN         NaN
163   2006-06-13   1356.20100      NaN      NaN         NaN
164   2006-06-14   1352.01200      NaN      NaN         NaN
165   2006-06-15   1140.32900      NaN      NaN         NaN
166   2006-06-16   1254.95400      NaN      NaN         NaN
167   2006-06-17   1103.62000      NaN      NaN         NaN
168   2006-06-18   1007.06700      NaN      NaN         NaN
169   2006-06-19   1351.98900      NaN      NaN         NaN
170   2006-06-20   1369.85500      NaN      NaN         NaN
171   2006-06-21   1372.48900      NaN      NaN         NaN
172   2006-06-22   1360.59400      NaN      NaN         NaN
173   2006-06-23   1316.96400      NaN      NaN         NaN
174   2006-06-24   1114.38600      NaN      NaN         NaN
175   2006-06-25   1028.86900      NaN      NaN         NaN
176   2006-06-26   1345.37900      NaN      NaN         NaN
177   2006-06-27   1352.60300      NaN      NaN         NaN
178   2006-06-28   1340.04200      NaN      NaN         NaN
179   2006-06-29   1343.63700      NaN      NaN         NaN
180   2006-06-30   1298.10300      NaN      NaN         NaN
181   2006-07-01   1106.61800      NaN      NaN         NaN
182   2006-07-02    997.89600      NaN      NaN         NaN
183   2006-07-03   1327.14300      NaN      NaN         NaN
184   2006-07-04   1356.52600      NaN      NaN         NaN
185   2006-07-05   1377.78100      NaN      NaN         NaN
186   2006-07-06   1377.99000      NaN      NaN         NaN
187   2006-07-07   1360.06100      NaN      NaN         NaN
188   2006-07-08   1138.65000      NaN      NaN         NaN
189   2006-07-09   1018.42300      NaN      NaN         NaN
190   2006-07-10   1335.24100      NaN      NaN         NaN
191   2006-07-11   1360.20800      NaN      NaN         NaN
192   2006-07-12   1358.22600      NaN      NaN         NaN
193   2006-07-13   1361.49300      NaN      NaN         NaN
194   2006-07-14   1324.45900      NaN      NaN         NaN
195   2006-07-15   1093.70100      NaN      NaN         NaN
196   2006-07-16    993.28900      NaN      NaN         NaN
197   2006-07-17   1305.24600      NaN      NaN         NaN
198   2006-07-18   1333.02900      NaN      NaN         NaN
199   2006-07-19   1342.70800      NaN      NaN         NaN
200   2006-07-20   1351.82300      NaN      NaN         NaN
201   2006-07-21   1333.34400      NaN      NaN         NaN
202   2006-07-22   1136.70000      NaN      NaN         NaN
203   2006-07-23   1025.40800      NaN      NaN         NaN
204   2006-07-24   1330.55700      NaN      NaN         NaN
205   2006-07-25   1349.82500      NaN      NaN         NaN
206   2006-07-26   1356.68900      NaN      NaN         NaN
207   2006-07-27   1348.64900      NaN      NaN         NaN
208   2006-07-28   1327.51400      NaN      NaN         NaN
209   2006-07-29   1122.14000      NaN      NaN         NaN
210   2006-07-30   1010.92200      NaN      NaN         NaN
211   2006-07-31   1289.92600      NaN      NaN         NaN
212   2006-08-01   1303.04800      NaN      NaN         NaN
213   2006-08-02   1291.21900      NaN      NaN         NaN
214   2006-08-03   1284.08900      NaN      NaN         NaN
215   2006-08-04   1262.64500      NaN      NaN         NaN
216   2006-08-05   1087.24500      NaN      NaN         NaN
217   2006-08-06    994.46600      NaN      NaN         NaN
218   2006-08-07   1268.80300      NaN      NaN         NaN
219   2006-08-08   1286.83900      NaN      NaN         NaN
220   2006-08-09   1285.66000      NaN      NaN         NaN
221   2006-08-10   1294.07700      NaN      NaN         NaN
222   2006-08-11   1274.98900      NaN      NaN         NaN
223   2006-08-12   1088.70900      NaN      NaN         NaN
224   2006-08-13    985.95900      NaN      NaN         NaN
225   2006-08-14   1266.84400      NaN      NaN         NaN
226   2006-08-15   1282.22000      NaN      NaN         NaN
227   2006-08-16   1292.05800      NaN      NaN         NaN
228   2006-08-17   1298.83700      NaN      NaN         NaN
229   2006-08-18   1290.86900      NaN      NaN         NaN
230   2006-08-19   1095.06600      NaN      NaN         NaN
231   2006-08-20   1023.16600      NaN      NaN         NaN
232   2006-08-21   1320.27400      NaN      NaN         NaN
233   2006-08-22   1341.31600      NaN      NaN         NaN
234   2006-08-23   1325.54500      NaN      NaN         NaN
235   2006-08-24   1330.92400      NaN      NaN         NaN
236   2006-08-25   1323.75500      NaN      NaN         NaN
237   2006-08-26   1126.49500      NaN      NaN         NaN
238   2006-08-27   1032.31900      NaN      NaN         NaN
239   2006-08-28   1344.45500      NaN      NaN         NaN
240   2006-08-29   1353.88500      NaN      NaN         NaN
241   2006-08-30   1373.31300      NaN      NaN         NaN
242   2006-08-31   1347.76300      NaN      NaN         NaN
243   2006-09-01   1339.46800      NaN      NaN         NaN
244   2006-09-02   1138.74200      NaN      NaN         NaN
245   2006-09-03   1093.76700      NaN      NaN         NaN
246   2006-09-04   1400.63400      NaN      NaN         NaN
247   2006-09-05   1398.36800      NaN      NaN         NaN
248   2006-09-06   1394.28000      NaN      NaN         NaN
249   2006-09-07   1403.40000      NaN      NaN         NaN
250   2006-09-08   1365.06100      NaN      NaN         NaN
251   2006-09-09   1135.57400      NaN      NaN         NaN
252   2006-09-10   1047.28500      NaN      NaN         NaN
253   2006-09-11   1379.24300      NaN      NaN         NaN
254   2006-09-12   1396.30300      NaN      NaN         NaN
255   2006-09-13   1398.32100      NaN      NaN         NaN
256   2006-09-14   1400.08700      NaN      NaN         NaN
257   2006-09-15   1397.50400      NaN      NaN         NaN
258   2006-09-16   1188.87600      NaN      NaN         NaN
259   2006-09-17   1064.35300      NaN      NaN         NaN
260   2006-09-18   1390.86300      NaN      NaN         NaN
261   2006-09-19   1404.47900      NaN      NaN         NaN
262   2006-09-20   1386.33200      NaN      NaN         NaN
263   2006-09-21   1385.80300      NaN      NaN         NaN
264   2006-09-22   1380.78300      NaN      NaN         NaN
265   2006-09-23   1175.30800      NaN      NaN         NaN
266   2006-09-24   1069.17500      NaN      NaN         NaN
267   2006-09-25   1401.10000      NaN      NaN         NaN
268   2006-09-26   1424.30400      NaN      NaN         NaN
269   2006-09-27   1417.32800      NaN      NaN         NaN
270   2006-09-28   1401.73100      NaN      NaN         NaN
271   2006-09-29   1383.45800      NaN      NaN         NaN
272   2006-09-30   1173.16800      NaN      NaN         NaN
273   2006-10-01   1058.26800      NaN      NaN         NaN
274   2006-10-02   1286.93200      NaN      NaN         NaN
275   2006-10-03   1116.57200      NaN      NaN         NaN
276   2006-10-04   1375.63600      NaN      NaN         NaN
277   2006-10-05   1397.45900      NaN      NaN         NaN
278   2006-10-06   1428.59200      NaN      NaN         NaN
279   2006-10-07   1227.91000      NaN      NaN         NaN
280   2006-10-08   1097.08700      NaN      NaN         NaN
281   2006-10-09   1406.12800      NaN      NaN         NaN
282   2006-10-10   1433.58800      NaN      NaN         NaN
283   2006-10-11   1429.99600      NaN      NaN         NaN
284   2006-10-12   1432.51200      NaN      NaN         NaN
285   2006-10-13   1426.50700      NaN      NaN         NaN
286   2006-10-14   1203.52600      NaN      NaN         NaN
287   2006-10-15   1089.68500      NaN      NaN         NaN
288   2006-10-16   1415.47400      NaN      NaN         NaN
289   2006-10-17   1445.88200      NaN      NaN         NaN
290   2006-10-18   1448.51100      NaN      NaN         NaN
291   2006-10-19   1451.64700      NaN      NaN         NaN
292   2006-10-20   1434.66600      NaN      NaN         NaN
293   2006-10-21   1232.33900      NaN      NaN         NaN
294   2006-10-22   1116.47300      NaN      NaN         NaN
295   2006-10-23   1461.80300      NaN      NaN         NaN
296   2006-10-24   1504.19200      NaN      NaN         NaN
297   2006-10-25   1468.36500      NaN      NaN         NaN
298   2006-10-26   1482.74700      NaN      NaN         NaN
299   2006-10-27   1476.27200      NaN      NaN         NaN
300   2006-10-28   1242.02400      NaN      NaN         NaN
301   2006-10-29   1173.76100      NaN      NaN         NaN
302   2006-10-30   1413.06600      NaN      NaN         NaN
303   2006-10-31   1460.39900      NaN      NaN         NaN
304   2006-11-01   1352.65800      NaN      NaN         NaN
305   2006-11-02   1479.07100      NaN      NaN         NaN
306   2006-11-03   1479.90000      NaN      NaN         NaN
307   2006-11-04   1297.95900      NaN      NaN         NaN
308   2006-11-05   1242.06400      NaN      NaN         NaN
309   2006-11-06   1521.54500      NaN      NaN         NaN
310   2006-11-07   1506.66900      NaN      NaN         NaN
311   2006-11-08   1518.36400      NaN      NaN         NaN
312   2006-11-09   1557.41100      NaN      NaN         NaN
313   2006-11-10   1484.26000      NaN      NaN         NaN
314   2006-11-11   1327.66400      NaN      NaN         NaN
315   2006-11-12   1226.64200      NaN      NaN         NaN
316   2006-11-13   1533.55400      NaN      NaN         NaN
317   2006-11-14   1523.36100      NaN      NaN         NaN
318   2006-11-15   1504.30100      NaN      NaN         NaN
319   2006-11-16   1490.77900      NaN      NaN         NaN
320   2006-11-17   1478.09500      NaN      NaN         NaN
321   2006-11-18   1270.72000      NaN      NaN         NaN
322   2006-11-19   1168.11400      NaN      NaN         NaN
323   2006-11-20   1509.71200      NaN      NaN         NaN
324   2006-11-21   1521.77800      NaN      NaN         NaN
325   2006-11-22   1512.51000      NaN      NaN         NaN
326   2006-11-23   1552.04400      NaN      NaN         NaN
327   2006-11-24   1494.08800      NaN      NaN         NaN
328   2006-11-25   1304.45300      NaN      NaN         NaN
329   2006-11-26   1155.54100      NaN      NaN         NaN
330   2006-11-27   1486.95900      NaN      NaN         NaN
331   2006-11-28   1520.42100      NaN      NaN         NaN